### ISSUE TITLE
Have you removed alarms from Hit Finder?

### ISSUE THREAD

**Issue by leemthai** [Kadauchi/mturk-suite#288]
I can't find alarms in the include list in the new hit finder? That was my favorite feature because  I used it to wake me up for special hits. I've tried pushbullet but it just doesn't work on my phone.

I checked the documentation at:
https://github.com/Kadauchi/mturk-suite/wiki/HIT-Finder

but it doesn't appear to be up to date with the current 3.2 version

Thanks!
 
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by Nounourson** [comment]
I also used the alarm **A LOT**, for the same reason as you did.
Removing this function is a big mistake in my opinion, you should really consider putting it back please... :/

**Comment by leemthai** [comment]
Yeah, it's actually my main use for Hit Finder, and MTS as a package.... sad

**Comment by remu007** [comment]
Also I have same issue. New HIT has no sound. I check all option but no solution. No sound for any New HIT. Please solve this issue. As soon as possible. Thank you very much.
![No sound](https://user-images.githubusercontent.com/48662693/104340491-f144d080-5522-11eb-9eed-60a54232397c.png)

**Comment by remu007** [comment]
If possible please update previous version.

**Comment by leemthai** [comment]
Is there any way to go back to 1.6? I would be happy with that if u don't plan on keeping alarms in new version :)

**Comment by brandonhellman** [comment]
The alarm and new hit sound will be coming back and you can expect it very soon.

**Comment by wpwentzell** [comment]
Just want to confirm I also have the issue of no new hit sound after updating to latest version. The catcher sound does work.

**Comment by Nounourson** [comment]
> The alarm and new hit sound will be coming back and you can expect it very soon.

Good to know, thanks!

**Comment by remu007** [comment]
Hello dear admin. I request you please also add New HIT sound and New HIT time. Just like as previous version. This new version have no New HIT time. I hope you understand. Thank you very much for your kind help.
![No sound](https://user-images.githubusercontent.com/48662693/104349716-792fd800-552d-11eb-9f4b-95afafb8396b.png)

**Comment by leemthai** [comment]
> The alarm and new hit sound will be coming back and you can expect it very soon.

Thank you very much, welcome news indeed!

**Comment by brandonhellman** [comment]
These features are back as of 3.3.2.

**Comment by leemthai** [comment]
I welcome back the alarm feature, thanks, was trying to get it set up for last night. There appears to be some kind of bug whereby the alarm keeps sounding for ALL favorites, not just the hits where the ALARM box is ticked.

I didn't have time to pin down the cause of the bug exactly. I think it happens only after a hit with the alarm status is ticked and the alarm goes off, and then every subsequent favorite that appears fires the alarm as well, regardless of whether the alarm button is ticked or not, but I think that is what is happening.

I tried refreshing the hit finder page but that didn't solve it. Non-alarm hits were still generating the alarm sounds every time.

Something is amiss anyway :)

Cheers,
