### ISSUE TITLE
Missing time

### ISSUE THREAD

**Issue by jfoz37** [Kadauchi/mturk-suite#289]
Previous versions of Hit Finder logged the time HITs were posted or last seen. This is an invaluable feature because some of us are not always around to check HIT Finder while it is running. After coming back from being AFK for a couple hours, the logged times in Hit Finder helped determine which HITs were still worth trying to catch. Please bring back this most useful feature.

**Comment by brandonhellman** [comment]
It will 100% be added back very soon. I'll close this issue once the update containing this feature is live.

**Comment by jfoz37** [comment]
Thanks for the update. I really appreciate all of the time and effort you have put into this great set of tools.

**Comment by brandonhellman** [comment]
Back with 3.3.2.
