### ISSUE TITLE
! Update Hit Tracker - message permanently on dashboard

### ISSUE THREAD

**Issue by leemthai** [Kadauchi/mturk-suite#290]
Every time I go back to:
https://worker.mturk.com/dashboard?ref=w_hdr_db

I get a message saying "Hit Tracker detected submitted Hits" etc. 

So I update hit tracker and then get the exact same message after doing another hit.

Feels like a bug.

**Comment by brandonhellman** [comment]
It definitely is a bug. Thanks for the report.

**Comment by brandonhellman** [comment]
Fixed with 3.2.1.
