### ISSUE TITLE
Requests to the server have been blocked by an extension.

### ISSUE THREAD

**Issue by Sunnil18** [Kadauchi/mturk-suite#303]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by brandonhellman** [comment]
This is fixed, just have to wait until 3.2.6 is published.

Can't access Catcher, Finder, Tracker? Right click the extension icon.

![img](https://i.gyazo.com/97994c9f4ca273494d38bf0808149a06.png)

**Comment by brandonhellman** [comment]
Not sure how much longer the webstores will take to publish it, could be today or later this week.

I've made a userscript to fix this in the meantime: https://greasyfork.org/en/scripts/423269-mts-sidebar-fix
