### ISSUE TITLE
Requests to the server have been blocked by an extension.

### ISSUE THREAD

**Issue by CyberSpyUsurped** [Kadauchi/mturk-suite#304]
Chrome extension no longer works in latest update. Get error "Requests to the server have been blocked by an extension."

**Comment by brandonhellman** [comment]
This is fixed, just have to wait until 3.2.6 is published.

Can't access Catcher, Finder, Tracker? Right click the extension icon.

![img](https://i.gyazo.com/97994c9f4ca273494d38bf0808149a06.png)

**Comment by Mavilalos** [comment]
Hi
This has just happened to me today!! I know you have a lot on your plate do you have any idea when version 3.2.6 will be published?

**Comment by brandonhellman** [comment]
Not sure how much longer the webstores will take to publish it, could be today or later this week.

I've made a userscript to fix this in the meantime: https://greasyfork.org/en/scripts/423269-mts-sidebar-fix

**Comment by Mavilalos** [comment]
Thank you for that very much appreciated!!! 👍
